name: parking_lot_game
description: A simple game to manage an imaginary parking lot.

publish_to: none
version: 1.1.1+4

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  google_fonts: ^6.2.1
  provider: ^6.1.2

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0

flutter:
  uses-material-design: true
